### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BabakR-alefba** [ehsannarmani/ComposeCharts#10]
`java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:437)
                                                                                                    	at ir.ehsannarmani.compose_charts.LineChartKt$LineChart$13$2$2.invokeSuspend$lambda$9(LineChart.kt:317)
                                                                                                    	at ir.ehsannarmani.compose_charts.LineChartKt$LineChart$13$2$2.$r8$lambda$xqNc49bpXaHelJXMCVxGfk1G8RY(Unknown Source:0)
                                                                                                    	at ir.ehsannarmani.compose_charts.LineChartKt$LineChart$13$2$2$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
                                                                                                    	at androidx.compose.foundation.gestures.DragGestureDetectorKt$detectDragGestures$5.invokeSuspend(DragGestureDetector.kt:190)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:164)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:504)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:493)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:665)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:544)
                                                                                                    	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:566)
                                                                                                    	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:317)
                                                                                                    	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:185)
                                                                                                    	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:104)
                                                                                                    	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:113)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1576)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1527)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1466)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:14568)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
2024-06-30 09:10:34.593 27479-27479 AndroidRuntime          ai.alefba.hamyarsanaat               E  	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
                                                                                                    	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                                    	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
                                                                                                    	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8160)
                                                                                                    	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8242)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:724)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@6bdcd87, androidx.compose.runtime.BroadcastFrameClock@d9d4b4, StandaloneCoroutine{Cancelling}@2c698dd, AndroidUiDispatcher@9109c52]
`

**Comment by ehsannarmani** [comment]
Hi, please mention your code and the situation which it crashes.

**Comment by BabakR-alefba** [comment]
First I show just one line on the chart. Then I update the chart with another 2 lines. then when I touch the chart to see the popup it crash.

**Comment by ehsannarmani** [comment]
@BabakR-alefba , Hi dear, thank you for reporting the problem.
This bug fixed in [0.0.10](https://github.com/ehsannarmani/ComposeCharts/tree/0.0.10).
